apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: scaling-notifier
  labels:
    app: scaling-notifier
spec:
  replicas: 1
  template:
    metadata:
      name: scaling-notifier
      labels:
        name: scaling-notifier
    spec:
      containers:
        - image: wbuchwalter/k8s-scaling-notifier
          name: scaling-notifier
          imagePullPolicy: Always
          command:
            - python
            - /app/main.py